<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Unrecoverable exceptions
        | Elasticsearch.Net and NEST: the .NET clients [7.x]
      | Elastic
    </title><link rel="home" href="index.html" title="Elasticsearch.Net and NEST: the .NET clients [7.x]" /><link rel="up" href="thrown-exceptions.html" title="Exceptions" /><link rel="prev" href="unexpected-exceptions.html" title="Unexpected exceptions" /><link rel="next" href="transports-and-pipelines.html" title="Transports and pipelines" /><meta name="DC.type" content="Learn/Docs/Clients/.Net/7.x" /><meta name="DC.subject" content="Clients" /><meta name="DC.identifier" content="7.x" /></head><body><div class="breadcrumbs"><span class="breadcrumb-link"><a href="index.html">Elasticsearch.Net and NEST:  the .NET clients
      [7.x]
    </a></span> » <span class="breadcrumb-link"><a href="api-conventions.html">API Conventions</a></span> » <span class="breadcrumb-link"><a href="thrown-exceptions.html">Exceptions</a></span> » <span class="breadcrumb-node">Unrecoverable exceptions</span></div><div class="navheader"><span class="prev"><a href="unexpected-exceptions.html">
              « 
              Unexpected exceptions</a>
           
        </span><span class="next">
           
          <a href="transports-and-pipelines.html">Transports and pipelines
               »
            </a></span></div><div class="section"><div class="titlepage"><div><div><h2 class="title"><a id="unrecoverable-exceptions"></a>Unrecoverable exceptions<a href="https://github.com/elastic/elasticsearch-net/edit/7.x/docs/client-concepts/connection-pooling/exceptions/unrecoverable-exceptions.asciidoc" class="edit_me" title="Edit this page on GitHub" rel="nofollow">edit</a></h2></div></div></div><p>Unrecoverable exceptions are <span class="emphasis"><em>expected</em></span> exceptions that are grounds to exit the client pipeline immediately.</p><div class="note admon"><div class="icon"><img alt="Note" src="images/icons/note.png" /></div><div class="admon_content"><p>What do we mean by <span class="emphasis"><em>expected</em></span> exceptions? Aren’t all exceptions <span class="emphasis"><em>exceptional</em></span>?</p><p>Well, there a some exceptions that can be thrown in the course of a request
that <span class="emphasis"><em>may</em></span> be expected, some of which can be retried on another node in the cluster, and some that cannot.
For example, an exception thrown when pinging a node throws an exception,
but this is an exception that the client expects can happen,
and can handle by trying a ping on another node. On the contrary, a bad authentication response from a node will throw an
exception, and the client understands that an exception under these circumstances should be handled by not retrying,
but by exiting the pipeline.</p></div></div><p>By default, the client won’t throw on any <code class="literal">ElasticsearchClientException</code> but instead return an invalid response
that can be detected by checking the <code class="literal">.IsValid</code> property on the response. You can change this behaviour with
by using <code class="literal">ThrowExceptions()</code> on <a class="link" href="configuration-options.html" title="Configuration options"><code class="literal">ConnectionSettings</code></a>.</p><div class="pre_wrapper lang-csharp"><pre class="programlisting prettyprint lang-csharp">var failures = Enum.GetValues(typeof(PipelineFailure)).Cast&lt;PipelineFailure&gt;();
foreach (var failure in failures)
{
    switch (failure)
    {
        /** The followinig pipeline failures are recoverable and will be retried */
        case PipelineFailure.PingFailure:
        case PipelineFailure.BadRequest:
        case PipelineFailure.BadResponse:
            var recoverable = new PipelineException(failure);
            recoverable.Recoverable.Should().BeTrue(failure.GetStringValue());
            break;

        /** The followinig pipeline failures are NOT recoverable and won't be retried */
        case PipelineFailure.BadAuthentication:
        case PipelineFailure.SniffFailure:
        case PipelineFailure.CouldNotStartSniffOnStartup:
        case PipelineFailure.MaxTimeoutReached:
        case PipelineFailure.MaxRetriesReached:
        case PipelineFailure.Unexpected:
        case PipelineFailure.NoNodesAttempted:
            var unrecoverable = new PipelineException(failure);
            unrecoverable.Recoverable.Should().BeFalse(failure.GetStringValue());
            break;
        default:
            throw new ArgumentOutOfRangeException(failure.GetStringValue());
    }
}</pre></div><p>As an example, let’s use our Virtual cluster test framework to set up a 10 node cluster
that always succeeds when pinged but fails with a 401 response when making client calls</p><div class="pre_wrapper lang-csharp"><pre class="programlisting prettyprint lang-csharp">var audit = new Auditor(() =&gt; VirtualClusterWith
    .Nodes(10)
    .Ping(r =&gt; r.SucceedAlways()) <a id="CO5-1"></a><i class="conum" data-value="1"></i>
    .ClientCalls(r =&gt; r.FailAlways(401)) <a id="CO5-2"></a><i class="conum" data-value="2"></i>
    .StaticConnectionPool()
    .AllDefaults()
);</pre></div><div class="calloutlist"><table border="0" summary="Callout list"><tr><td width="5%" valign="top" align="left"><p><a href="#CO5-1"><i class="conum" data-value="1"></i></a> </p></td><td valign="top" align="left"><p>Always succeed on ping</p></td></tr><tr><td width="5%" valign="top" align="left"><p><a href="#CO5-2"><i class="conum" data-value="2"></i></a> </p></td><td valign="top" align="left"><p>…​but always fail on calls with a 401 Bad Authentication response</p></td></tr></table></div><p>Now, let’s make a client call. We’ll see that the first audit event is a successful ping
followed by a bad response as a result of the 401 bad authentication response</p><div class="pre_wrapper lang-csharp"><pre class="programlisting prettyprint lang-csharp">audit = await audit.TraceElasticsearchException(
    new ClientCall {
        { AuditEvent.PingSuccess, 9200 }, <a id="CO6-1"></a><i class="conum" data-value="1"></i>
        { AuditEvent.BadResponse, 9200 }, <a id="CO6-2"></a><i class="conum" data-value="2"></i>
    },
    exception =&gt;
    {
        exception.FailureReason
            .Should().Be(PipelineFailure.BadAuthentication); <a id="CO6-3"></a><i class="conum" data-value="3"></i>
    }
);</pre></div><div class="calloutlist"><table border="0" summary="Callout list"><tr><td width="5%" valign="top" align="left"><p><a href="#CO6-1"><i class="conum" data-value="1"></i></a> </p></td><td valign="top" align="left"><p>First call results in a successful ping</p></td></tr><tr><td width="5%" valign="top" align="left"><p><a href="#CO6-2"><i class="conum" data-value="2"></i></a> </p></td><td valign="top" align="left"><p>Second call results in a bad response</p></td></tr><tr><td width="5%" valign="top" align="left"><p><a href="#CO6-3"><i class="conum" data-value="3"></i></a> </p></td><td valign="top" align="left"><p>The reason for the bad response is Bad Authentication</p></td></tr></table></div><p>When a bad authentication response occurs, the client attempts to deserialize the response body returned;</p><p>In some setups you might be running behind a proxy and you might need to prevent the client from trying to deserialize
bad json. In the following example an HTML response is return but with an application/json content type. If the proxy is not
under your control you would need to be able to fix this in the client. Here we make the client aware that 401 responses
should never be deserialized by calling <code class="literal">SkipDeserializationForStatusCodes()</code> on <code class="literal">ConnectionSettings</code>.</p><div class="pre_wrapper lang-csharp"><pre class="programlisting prettyprint lang-csharp">var audit = new Auditor(() =&gt; VirtualClusterWith
    .Nodes(10)
    .Ping(r =&gt; r.SucceedAlways())
    .ClientCalls(r =&gt; r.FailAlways(401).ReturnByteResponse(HtmlNginx401Response, "application/json")) <a id="CO7-1"></a><i class="conum" data-value="1"></i>
    .StaticConnectionPool()
    .Settings(s=&gt;s.SkipDeserializationForStatusCodes(401))
);

audit = await audit.TraceElasticsearchException(
    new ClientCall {
        { AuditEvent.PingSuccess, 9200 },
        { AuditEvent.BadResponse, 9200 },
    },
    (e) =&gt;
    {
        e.FailureReason.Should().Be(PipelineFailure.BadAuthentication);
        e.Response.HttpStatusCode.Should().Be(401);
        e.Response.ResponseBodyInBytes.Should().BeNull(); <a id="CO7-2"></a><i class="conum" data-value="2"></i>
    }
);</pre></div><div class="calloutlist"><table border="0" summary="Callout list"><tr><td width="5%" valign="top" align="left"><p><a href="#CO7-1"><i class="conum" data-value="1"></i></a> </p></td><td valign="top" align="left"><p>Always return a 401 bad response with a HTML response on client calls</p></td></tr><tr><td width="5%" valign="top" align="left"><p><a href="#CO7-2"><i class="conum" data-value="2"></i></a> </p></td><td valign="top" align="left"><p>Assert that the response body bytes are null</p></td></tr></table></div><p>Now in this example, by turning on <code class="literal">DisableDirectStreaming()</code> on <code class="literal">ConnectionSettings</code>, we see the same behaviour exhibited
as before, but this time however, the response body bytes are captured in the response and can be inspected.
Also note that in this example the 401 returns the correct mime type for html so the client wont try to deserialize to json and
we no longer need to set <code class="literal">SkipDeserializationForStatusCodes()</code></p><div class="pre_wrapper lang-csharp"><pre class="programlisting prettyprint lang-csharp">var audit = new Auditor(() =&gt; VirtualClusterWith
    .Nodes(10)
    .Ping(r =&gt; r.SucceedAlways())
    .ClientCalls(r =&gt; r.FailAlways(401).ReturnByteResponse(HtmlNginx401Response, "text/html"))
    .StaticConnectionPool()
    .Settings(s =&gt; s.DisableDirectStreaming())
);

audit = await audit.TraceElasticsearchException(
    new ClientCall {
        { AuditEvent.PingSuccess, 9200 },
        { AuditEvent.BadResponse, 9200 },
    },
    (e) =&gt;
    {
        e.FailureReason.Should().Be(PipelineFailure.BadAuthentication);
        e.Response.HttpStatusCode.Should().Be(401);
        e.Response.ResponseBodyInBytes.Should().NotBeNull(); <a id="CO8-1"></a><i class="conum" data-value="1"></i>
        var responseString = Encoding.UTF8.GetString(e.Response.ResponseBodyInBytes);
        responseString.Should().Contain("nginx/"); <a id="CO8-2"></a><i class="conum" data-value="2"></i>
        e.DebugInformation.Should().Contain("nginx/");
    }
);</pre></div><div class="calloutlist"><table border="0" summary="Callout list"><tr><td width="5%" valign="top" align="left"><p><a href="#CO8-1"><i class="conum" data-value="1"></i></a> </p></td><td valign="top" align="left"><p>Response bytes are set on the response</p></td></tr><tr><td width="5%" valign="top" align="left"><p><a href="#CO8-2"><i class="conum" data-value="2"></i></a> </p></td><td valign="top" align="left"><p>Assert that the response contains <code class="literal">"nginx/"</code></p></td></tr></table></div></div><div class="navfooter"><span class="prev"><a href="unexpected-exceptions.html">
              « 
              Unexpected exceptions</a>
           
        </span><span class="next">
           
          <a href="transports-and-pipelines.html">Transports and pipelines
               »
            </a></span></div></body></html>
